tuple1=(1,6,8,9,"Livre","Soda")
tuple2=(2,6,9,0,None)
tuple3=(6,9,0)
print("Tuple1:",tuple1)
print("Tuple2:",tuple2)
print("Tuple3:",tuple3)

print('Longueur du tuple1 est:',len(tuple1))
print('Longueur du tuple2 est:',len(tuple2))
print('Longueur du tuple3 est:',len(tuple3))
